In [1]:
import numpy as np

In [2]:
def calculate_distance ( start = (2,4) , end = (2,4)):
    return np.sqrt((end[1] - start[1])**2 +(end[0] - start[0])**2)

In [31]:
nombreC = int(input("entrer nmber de centre:"))
pointC = []
for i in range (nombreC):
    x=int(input(f"Entrer x{i} :"))
    y=int(input(f"Entrer y{i} :"))
    pointC.append([x,y])
number  = int(input("entrer nmber de point:"))

point = []

distance = []

for i in range (number):
    x=int(input(f"Entrer x{i} :"))
    y=int(input(f"Entrer y{i} :"))
    point.append([x,y])
for i in range(nombreC):
    d=[]
    for j in range(number):
        d.append(calculate_distance((pointC[i][0],pointC[i][1]),(point[j][0],point[j][1])))
    distance.append(d)
print(distance)


[[2.0, 9.848857801796104, 7.810249675906654, 5.830951894845301, 11.40175425099138, 22.47220505424423, 123.79418403139947], [5.0, 6.324555320336759, 2.0, 1.0, 5.0, 15.811388300841896, 117.51595636338071]]


In [32]:
resultat= []
for i in range(nombreC):
    resultat.append([])

for i in range(number):
    minum=None
    imin=None
    xmin=None
    ymin=None
    for j in range(nombreC):
        if(minum==None or minum>distance[j][i]):
            minum=distance[j][i]
            imin=j
            xmin=point[i][0]
            ymin=point[i][1]
    if imin!=None:
        resultat[imin].append([i,xmin,ymin])
for i in range(len(resultat)):
    print(f"les point de centre {i}\n")
    for j in range(len(resultat[i])):
        print(f"point N {resultat[i][j][0]} x={resultat[i][j][1]}  y={resultat[i][j][2]}")

les point de centre 0

point N 0 x=0  y=2
les point de centre 1

point N 1 x=9  y=4
point N 2 x=5  y=6
point N 3 x=3  y=5
point N 4 x=7  y=9
point N 5 x=12  y=19
point N 6 x=90  y=85


In [5]:
# list of points

points = []

number_of_point = int ( input("enter the number of point ") )

for i in range(number_of_point):
    x = int( input(f'enter the X{i+1} cordinate:') )
    y = int( input(f'enter the Y{i+1} cordinate:') )
    points.append((x,y))


distance_of_points = np.zeros((number_of_point , number_of_point))

# array of distance between each point

for row in range(number_of_point):
    
    for column in range(number_of_point):

        distance_of_points[row][column] = calculate_distance(points[row] , points[column])



the cordinate of each point [(1, 5), (6, 4), (9, 2), (1, 4), (3, 8), (7, 2)]
the distance between each points 
[[0.         5.09901951 8.54400375 1.         3.60555128 6.70820393]
 [5.09901951 0.         3.60555128 5.         5.         2.23606798]
 [8.54400375 3.60555128 0.         8.24621125 8.48528137 2.        ]
 [1.         5.         8.24621125 0.         4.47213595 6.32455532]
 [3.60555128 5.         8.48528137 4.47213595 0.         7.21110255]
 [6.70820393 2.23606798 2.         6.32455532 7.21110255 0.        ]]


In [22]:
print(f"the cordinate of each point {points}")
print(f"the distance between each points \n{distance_of_points}")

the cordinate of each point [(1, 5), (6, 4), (9, 2), (1, 4), (3, 8), (7, 2)]
the distance between each points 
[[0.         5.09901951 8.54400375 1.         3.60555128 6.70820393]
 [5.09901951 0.         3.60555128 5.         5.         2.23606798]
 [8.54400375 3.60555128 0.         8.24621125 8.48528137 2.        ]
 [1.         5.         8.24621125 0.         4.47213595 6.32455532]
 [3.60555128 5.         8.48528137 4.47213595 0.         7.21110255]
 [6.70820393 2.23606798 2.         6.32455532 7.21110255 0.        ]]


In [16]:
# define the center 
center_cordinate = []
distance_between_center = []
result = []
number_of_center = int( input('enter the number of center') )

for i in range (number_of_center):
    x = int( input(f'enter the center X{i+1} cordinate:') )
    y = int( input(f'enter the center Y{i+1} cordinate:') )
    center_cordinate.append((x,y))
    distance_between_center.append([])
    result.append([])



for center_index , center in enumerate(center_cordinate):
    for point_index , point in enumerate(points):
        distance_between_center[center_index].append(calculate_distance(center , point ))
        


In [17]:
print(f'the cordinate of the centers {center_cordinate}\n')
print(f'the distance between each point and each center :\n {distance_between_center}')

the cordinate of the centers [(1, 2), (3, 1), (2, 2)]

the distance between each point and each center :
 [[3.0, 5.385164807134504, 8.0, 2.0, 6.324555320336759, 6.0], [4.47213595499958, 4.242640687119285, 6.082762530298219, 3.605551275463989, 7.0, 4.123105625617661], [3.1622776601683795, 4.47213595499958, 7.0, 2.23606797749979, 6.082762530298219, 5.0]]


In [18]:
# classification of the point depending on there distance

for index in range(number_of_point):
    compare_list = []
    for sublist in distance_between_center:
        compare_list.append(sublist[index])
    close_to_center_index = compare_list.index(min(compare_list))
    result[close_to_center_index].append(points[index])

In [21]:
# print(f'the result of classification :\n {result}')
for center_index , center_class in enumerate(result):
    print(f'the points {center_class} belong to the center {center_cordinate[center_index]}')

the points [(1, 5), (1, 4)] belong to the center (1, 2)
the points [(6, 4), (9, 2), (7, 2)] belong to the center (3, 1)
the points [(3, 8)] belong to the center (2, 2)
