### Implimentation of the gived example in the Gmail 

In [31]:
import numpy as np

inputs = np.array([ 
    0,#X1
    1,#X2
    1,#X3
])

weight_layer_1 = np.array([
    [0.351,-0.097 ,0.457],
    [1.076 , -0.165 , -0.165],
    [1.116 , 0.542 , -0.331]
    ])

weight_layer_2 = np.array([0.383,-0.327 ,-0.329])

inputs , weight_layer_1

(array([0, 1, 1]),
 array([[ 0.351, -0.097,  0.457],
        [ 1.076, -0.165, -0.165],
        [ 1.116,  0.542, -0.331]]))

1) activation function

In [32]:
def segmoid (sum):
    return 1/(1+np.exp(-sum))

In [33]:
def model(inputs , weight):
    sum = np.dot(inputs , weight)
    return sum

In [34]:
activation_layer_1 = segmoid(model(inputs ,weight_layer_1))
activation_layer_2 = segmoid(model(activation_layer_1 , weight_layer_2))

activation_layer_1 , activation_layer_2

(array([0.8995288 , 0.59314934, 0.37848114]), 0.5065094829653212)

In [ ]:
def gradient ():
    pass 

### Implimentation of the nuerale network given in the Class

1) Define the Data

In [46]:
inputs = np.array([0.1 , 0.3])

weight_layer_1  = np.array([
    [0.5 , 0.2],
    [0.62 , 0.2],
    ])

weight_layer_2  = np.array([0.2 , 0.3],)

bias_layer_1 = np.array([0.4 , -0.1])

bias_layer_2 = np.array([1.83])


In [47]:
def model(inputs , weight , bias):
    sum = np.dot(inputs , weight) +bias
    return sum

In [48]:
activation_layer_1 = segmoid(model(inputs ,weight_layer_1 , bias_layer_1))
activation_layer_2 = segmoid(model(activation_layer_1 ,weight_layer_2 , bias_layer_2))

activation_layer_1 , activation_layer_2

(array([0.6538487 , 0.49500017]), array([0.89180089]))

In [49]:
# need the gradiant function and the update function