# TP1
## Exercice 1
### 1

In [106]:
import numpy as np

# Create a row vector
row_vector = np.array([[1],[2],[3],])
print("vecteur: \n" , row_vector)
print("\n shape v :",row_vector.shape ,"\n") # Output: (3,1)

# Create a column vector
column_vector = np.array([[1,2,3]])
print("colones : \n",column_vector)
print("\n shape c :",column_vector.shape) # Output: (1,3)



vecteur: 
 [[1]
 [2]
 [3]]

 shape v : (3, 1) 

colones : 
 [[1 2 3]]

 shape c : (1, 3)


### 2

In [107]:
# Transpose the row vector into a column vector
transposed_column_vector = row_vector.T
print(transposed_column_vector.shape) # Output: (1, 3)

# Calculate the L1 norm
l1_norm = np.linalg.norm(transposed_column_vector, ord=1) # l1 = nombre de colone (1+1+1)
print("L1 : ",l1_norm)

# Calculate the L2 norm
l2_norm = np.linalg.norm(transposed_column_vector) # l2 = racine de (1^2+2^2+3^2)
print("L2 : ",l2_norm)

# Calculate the L∞ norm
linf_norm = np.linalg.norm(transposed_column_vector, ord=np.inf) #l inf = la somme de colone (1+2+3)
print("L_inf : ",linf_norm)


(1, 3)
L1 :  3.0
L2 :  3.7416573867739413
L_inf :  6.0


### 3

In [108]:
# Define two vectors
v = np.array([10, 9, 3])
w = np.array([2, 5, 12])

# Compute dot product
dot_product = np.inner(v, w) #produit : v*w=10*2+9*5+3*12

# Compute magnitudes
v_magnitude = np.linalg.norm(v) # l2 deja defini 
w_magnitude = np.linalg.norm(w)

# Compute angle in radians
angle_radians = np.arccos(dot_product / (v_magnitude * w_magnitude)) # angle= cos^-1( [produit(v*w)]/[l2(v)*l2(w)] )

# Print angle
print(angle_radians)


0.979924710443726


### 4

In [109]:
# Define two vectors
v = np.array([0, 2, 0])
w = np.array([3, 0, 0])

# Compute cross product
cross_product = np.cross(v, w) # cross_product = [ (v2 * w3 - v3 * w2), (v3 * w1 - v1 * w3), (v1 * w2 - v2 * w1) ]
                                #                  ( 2*0     -   0*0)  ,  (  0*3     -   0*0) ,   (  0*0   - 2*3 )
# Print cross product
print(cross_product)


[ 0  0 -6]


### 5

In [110]:
# Define row vectors
v = np.array([0, 3, 2])
w = np.array([4, 1, 1])
u = np.array([0, 2, 0])
x = np.array([8, 1, 4])
#Create matrix of coefficients
coefficient_matrix = np.column_stack((v, w, u)) # transforme the vectors a coloms in one matrix 
print(coefficient_matrix)
#Solve system of linear equations
solution = np.linalg.solve(coefficient_matrix, x)
#Print solution
print(solution)

[[0 4 0]
 [3 1 2]
 [2 1 0]]
[ 1.  2. -2.]


## Exercice 2
## 1 
#### methode 1

In [111]:
import numpy as np

# Define matrices P and Q
P = np.array([[1, 7], [2, 3], [5, 0]]) # (3,2)
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]]) #(2,4)


# Compute matrix product of P and Q
try:
    P_Q = np.matmul(P, Q)
    print(" \n Matrix product of P and Q: \n ", P_Q)
except Exception as e:
    print(e)

# Compute matrix product of Q and P
try:
    Q_P = np.matmul(Q, P)
    print(" \n Matrix product of Q and P: \n ", Q_P)
except Exception as e:
    print(e)


 
 Matrix product of P and Q: 
  [[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)


## 1 
### methode2

In [2]:
import numpy as np

P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])

product = np.dot(P, Q)
print(product)


[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


### 2

In [113]:
M = np.array([[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]])
det_M = np.linalg.det(M)
print(det_M)
I = np.eye(4)

product = np.dot(M, I)
print(product)


-38.000000000000014
[[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


## 2 
### methode 2

In [27]:
# Define matrix M
M = np.array([[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]])


# Compute determinant of M
det_M = np.linalg.det(M)
print("Determinant of M: ", det_M)#calcule de determinant 

# Create identity matrix I
I = np.eye(4)
print("\n I:\n",I)

# Multiply M and I
MI = np.matmul(M, I)
print(" \n Multiplication of M and I: \n", MI)# toujour matrice identifiant X matrix* = matrix*




Determinant of M:  -38.000000000000014

 I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 
 Multiplication of M and I: 
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


### 3

In [115]:
# Compute inverse of M
inv_M = np.linalg.inv(M)
print("Inverse of M: \n", inv_M)

# Define matrix P
P = np.array([[0, 1, 0], [0, 0, 0], [1, 0, 1]])

# Compute determinant of P
det_P = np.linalg.det(P)
print("Determinant of P: ", det_P)

# Compute inverse of P
try:
    inv_P = np.linalg.inv(P)
    print("Inverse of P: \n", inv_P)        #if det(A)=0 we c'est impossible d'inverser la matrix 
except Exception as e:
    print(e)


Inverse of M: 
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
Determinant of P:  0.0
Singular matrix


### 4

In [21]:
# Define matrix A and y
A = np.array([[1, 1, 0], [0, 1, 0], [1, 0, 1]])
y = np.array([[1], [2], [1]])

# Compute condition number of A
cond_A = np.linalg.cond(A) # cond(A) = ||A|| * ||A^(-1)||
print("Condition number of A: ", cond_A)

# test = np.linalg.norm(A) * np.linalg.norm(np.linalg.inv(A))
# print('test:',test)

# Compute rank of A
rank_A = np.linalg.matrix_rank(A)
print("Rank of A: ", rank_A) # rank = min (nb lign ou  nb column )

# Get augmented matrix [A, y]
aug_A = np.column_stack((A, y)) # cancatination
print("Augmented matrix [A, y]: \n", aug_A)


Condition number of A:  5.878367738045564
Rank of A:  3
Augmented matrix [A, y]: 
 [[1 1 0 2 1]
 [0 1 0 4 2]
 [1 0 1 2 1]]


### 5

In [117]:
# Define system of linear equations
A = np.array([[8, 3, -3], [-2, -8, 5], [3, 5, 10]])
b = np.array([14, 5, 8])

# Define initial values for x
x = np.array([0, 0, 0])

# Define threshold 𝜖
eps = 0.01

# Define maximum number of iterations
max_iter = 100

# Initialize error and iteration counter
error = float('inf')
iter_count = 0

# Implement Gauss-Seidel method
while error > eps and iter_count < max_iter:
    x_new = np.copy(x)
    for i in range(len(A)):
        s = 0
        for j in range(len(A)):
            if j != i:
                s += A[i][j] * x[j]
        x_new[i] = (b[i] - s) / A[i][i]
    error = np.linalg.norm(x_new - x)
    iter_count += 1
    x = np.copy(x_new)

# Print solution
print("Solution: ", x)

# Print number of iterations
print("Number of iterations: ", iter_count)

# Print error
print("Error: ", error)


Solution:  [1 0 0]
Number of iterations:  2
Error:  0.0


### 6


In [118]:
x = np.linalg.solve(A, b)
print("Solution: ", x)


Solution:  [ 2.27413127 -0.85328185  0.54440154]


### 7

A * X = b ===>  x = A^-1 * b

In [119]:
x = np.matmul(np.linalg.inv(A), b)
print("Solution: ", x)


Solution:  [ 2.27413127 -0.85328185  0.54440154]


### 8

In [32]:

# Define matrix A
A = np.array([[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]])

# Compute eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print eigenvalues
print("Eigenvalues: ", eigenvalues)

# Print eigenvectors
print("\n Eigenvectors: \n", eigenvectors)


Eigenvalues:  [ 7.0796991 +0.j         -1.83972579+3.16634801j -1.83972579-3.16634801j
 -0.40024753+0.j        ]

 Eigenvectors: 
 [[-0.43431157+0.j          0.3205899 +0.06382272j  0.3205899 -0.06382272j
  -0.81845667+0.j        ]
 [-0.74012233+0.j         -0.72163469+0.j         -0.72163469-0.j
  -0.36173299+0.j        ]
 [-0.25110615+0.j          0.20764965-0.3620403j   0.20764965+0.3620403j
   0.38781761+0.j        ]
 [-0.44781481+0.j          0.14791243+0.41990774j  0.14791243-0.41990774j
   0.22107788+0.j        ]]
