# Unkwon Part 

In [1]:
import numpy as np 

a=np.array([[1,-4,4],[2,6,4],[2,3,6]])
#b=np.array([2,3,4])
#print(type(.7))

def calcule(A):
    n,m=A.shape
    if n!=m:
        print('la matrice doit etre carree')
    elif(n==2):
        return A[0,0]*A[1,1]-A[0,1]*A[1,0]
    else:
        return A[0,0]*calcule(np.array([[A[1,1],A[1,2]],[A[2,1],A[2,2]]]))\
            -A[0,1]*calcule(np.array([[A[1,1],A[1,2]],[A[2,1],A[2,2]]]))\
                +A[0,2]*calcule(np.array([[A[1,0],A[1,1]],[A[2,0],A[2,1]]]))

print(calcule(a))

96


# EXercice 1 (Vectors).

### Question 1

Create a row vector and column vector, and show the shape of the vectors.

In [2]:
import numpy as np

# Create a row vector
row_vector = np.array([[1, 2, 3]])
print(row_vector.shape) # Output: (1,3)

# Create a column vector
column_vector = row_vector.T
print(column_vector.shape) # Output: (3, 1)



(1, 3)
(3, 1)


### Question 2

(2) Transpose the row vector we defined above into a column vector and calculate the
L1 , L2 , and L∞ norm of it. Verify that the L∞ norm of a vector is equivalent to
the maximum value of the elements in the vector.

In [3]:
# Transpose the row vector into a column vector
transposed_column_vector = row_vector.T
print("shape of transposed_column_vector:",transposed_column_vector.shape) # Output: (3, 1)

# Calculate the L1 norm
l1_norm = np.linalg.norm(transposed_column_vector, ord=1)
print("L1 norm:", l1_norm)

# Calculate the L2 norm
l2_norm = np.linalg.norm(transposed_column_vector)
print("L2 norm:", l2_norm)

# Calculate the L∞ norm
linf_norm = np.linalg.norm(transposed_column_vector, ord=np.inf)
print("L∞ norm:", linf_norm)

# Maximum value of the elements in the vector
max_val = np.max(column_vector)
print("Maximum value of the elements in the vector:", max_val)

shape of transposed_column_vector: (3, 1)
L1 norm: 6.0
L2 norm: 3.7416573867739413
L∞ norm: 3.0
Maximum value of the elements in the vector: 3


### Question 3

Compute the angle between the vectors v = [10, 9, 3] and w = [2, 5, 12].

We already know that V * W = |V| * |W| * COS(Alpha)

In [4]:
import numpy as np

v = np.array([10, 9, 3])
w = np.array([2, 5, 12])

dot_product = np.dot(v, w)
norm_v = np.linalg.norm(v)
norm_w = np.linalg.norm(w)
cos_theta = dot_product / (norm_v * norm_w)
angle = np.arccos(cos_theta)

print("Angle (in radians):", angle)

angle_deg = np.degrees(angle)
print("Angle (in degrees):", angle_deg)


Angle (in radians): 0.979924710443726
Angle (in degrees): 56.14555014900476


### Question 4

Given the vectors v = [0, 2, 0] and w = [3, 0, 0], use the Numpy function cross to
compute the cross product of v and w.

In [5]:
# Define two vectors
v = np.array([0, 2, 0])
w = np.array([3, 0, 0])

# Compute cross product
cross_product = np.cross(v, w) #TODO:figure out how the cross function work

# Print cross product
print("Cross product:", cross_product)


Cross product: [ 0  0 -6]


### Question 5

Given the row vectors v = [0, 3, 2], w = [4, 1, 1], and u = [0, 2, 0], write the vector
x = [8, 1, 4] as a linear combination of v, w, and u.

a * 0 + b * 4 + c * 0 = 8 <br>
a * 3 + b * 1 + c * 2 = 1 <br>
a * 2 + b * 1 + c * 0 = 4 <br>

We know that <B> Coffecient Matrix * solution = X  </B>

In [6]:
# Define row vectors
v = np.array([0, 3, 2])
w = np.array([4, 1, 1])
u = np.array([0, 2, 0])
x = np.array([8, 1, 4])

#Create matrix of coefficients
coefficient_matrix = np.column_stack((v, w, u))

#Solve system of linear equations
solution = np.linalg.solve(coefficient_matrix, x)

#Print solution
print("Solution",solution)

#cheking the solution 
if np.allclose(np.dot(coefficient_matrix , solution) , x):
    print("the solution are correct ")
else:
    print("the solution are not correct ")


Solution [ 1.  2. -2.]
the solution are correct 


# Excercice 2

### Question 1

Let the Python matrices P = [[1, 7], [2, 3], [5, 0]] and Q = [[2, 6, 3, 1], [1, 2, 3, 4]].
Compute the matrix product of P and Q. Show that the product of Q and P will
produce an error.

In [7]:
import numpy as np

#Define the matrix
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])


print("the shape of array Q:", Q.shape)
print("the shape of array P:", P.shape)

try:
    #to show that the the product of Q and P will produce an Error just uncoment the next instruction 
    #R = np.dot(Q, P)
    R = np.dot(P, Q)
    print("\n The Matrix Product:\n",R)
    print("\n The shape Matrix Product:",R.shape)

except ValueError:
    print("Error: The number of columns in P is not equal to the number of rows in Q.")

the shape of array Q: (2, 4)
the shape of array P: (3, 2)

 The Matrix Product:
 [[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]

 The shape Matrix Product: (3, 4)


### Question 2

Use Python to find the determinant of the matrix <br><B>M = [[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]].</B><br>
Use the np.eye function to produce a 4 ? 4 identity matrix, I. Multiply M by I to
show that the result is M.

multiplying a matrix by the identity matrix leaves the matrix unchanged.

In [8]:
#define the matrix
M = np.array([[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]])

#find the determinant of array M using the det function 
determinant = np.linalg.det(M)
print("Determinant of M: ",determinant)

#create the identity matrix I 4*4
I = np.eye(4)
M_I = np.dot(M,I)
if np.allclose(M , M_I):
    print ("The M array and the M*I are equal")
else:
    print ("The M array and the M*I are not equal")

print("M*I:\n",M_I)


Determinant of M:  -38.000000000000014
The M array and the M*I are equal
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


### Question 3

The matrix M (in the previous example) has a nonzero determinant. Compute the
inverse of M. Show that the matrix P = [[0, 1, 0], [0, 0, 0], [1, 0, 1]] has a determinant
value of 0 and therefore has no inverse.

In [9]:
try:
    inverse_M = np.linalg.inv(M)
    print("Inverse of M:\n",inverse_M)
except np.linalg.LinAlgError:
    print("\n Error: The matrix has no inverse.")

P = np.array([[0, 1, 0], [0, 0, 0], [1, 0, 1]])
determinant_P = np.linalg.det(P)
if determinant_P == 0:
    print("\n Error: The matrix has no inverse.")
else:
    inverse_P = np.linalg.inv(P)
    print("\n Inverse of P: ",inverse_P)


Inverse of M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]

 Error: The matrix has no inverse.


###  Question 4

Matrix A = [[1, 1, 0], [0, 1, 0], [1, 0, 1]], compute the condition number and rank for
this matrix. If y = [[1], [2], [1]], get the augmented matrix [A, y].

In [23]:

A = np.array([[1, 1, 0], [0, 1, 0], [1, 0, 1]])
y = np.array([[1], [2], [1]])


# Find the condition number of A using numpy's linalg.cond function
condition_number = np.linalg.cond(A)
print("Condition Number:", condition_number)

# Find the rank of A using numpy's linalg.matrix_rank function
rank = np.linalg.matrix_rank(A)
print("Rank:", rank)

# Augmented matrix [A, y]
augmented_matrix = np.concatenate((A, y), axis=1)
print("Augmented Matrix:")
print(augmented_matrix)


Condition Number: 4.048917339522305
Rank: 3
Augmented Matrix:
[[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


### Question 5

 Solve the following system of linear equations using Gauss-Seidel method, use a
pre-defined threshold tool = 0.01. Do remember to check if the converge condition is
satisfied or not.


8x1 + 3x2 − 3x3 = 14


−2x1 − 8x2 + 5x3 = 5


3x1 + 5x2 + 10x3 = 8

In [28]:

# Define the coefficients of the system of linear equations
A = np.array([[8, 3, -3], [-2, -8, 5], [3, 5, 10]])
b = np.array([14, 5, 8])

# Define the threshold 
threshold = 0.01

# Define the maximum number of iterations
max_iterations = 1000

# Choose an initial guess for the solution vector
x = np.array([0, 0, 0])

# Initialize the iteration counter
iteration = 0

# Repeat the following steps until the solution converges or the maximum number of iterations is reached
while iteration < max_iterations:
    # Store the previous solution
    x_prev = x.copy()
    
    # Update the first component of x
    x[0] = (b[0] - 3 * x[1] + 3 * x[2]) / 8
    
    # Update the second component of x
    x[1] = (b[1] + 2 * x[0] - 5 * x[2]) / -8
    
    # Update the third component of x
    x[2] = (b[2] - 3 * x[0] - 5 * x[1]) / 10
    
    # Check if the solution has converged
    if np.linalg.norm(np.subtract(x, x_prev)) / (np.linalg.norm(x_prev) + 1e-9) <= threshold:
        break
    
    # Increment the iteration counter
    iteration += 1

# Print the solution
print(f"The solution is x = {x} after {iteration} iterations")


The solution is x = [1 0 0] after 1 iterations


### Question 6

Use numpy.linalg.solve to solve the above equations

In [32]:
result = np.linalg.solve(A,b)
print("solution :", result)


solution : [ 2.27413127 -0.85328185  0.54440154]


### Question 7

Try to solve the above equations using the matrix inversion approach

<b>A * X = b ==>  X =  A<up>-1</up> * b </b>

In [34]:
try:
    inverse_a = np.linalg.inv(A)
    result = np.dot(inverse_a,b)
    print("The Solution Matrix inversion approach: ",result)
except np.linalg.LinAlgError:
    print("Error: The matrix has no inverse.")


The Solution Matrix inversion approach:  [ 2.27413127 -0.85328185  0.54440154]
[ 2.27413127 -0.85328185  0.54440154]


### Question 8

Calculate the eigenvalues and eigenvectors for matrix A = [[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]]

In [35]:
A = np.array([[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues: \n", eigenvalues)
print("\n Eigenvectors: \n", eigenvectors)


Eigenvalues: 
 [ 7.0796991 +0.j         -1.83972579+3.16634801j -1.83972579-3.16634801j
 -0.40024753+0.j        ]

 Eigenvectors: 
 [[-0.43431157+0.j          0.3205899 +0.06382272j  0.3205899 -0.06382272j
  -0.81845667+0.j        ]
 [-0.74012233+0.j         -0.72163469+0.j         -0.72163469-0.j
  -0.36173299+0.j        ]
 [-0.25110615+0.j          0.20764965-0.3620403j   0.20764965+0.3620403j
   0.38781761+0.j        ]
 [-0.44781481+0.j          0.14791243+0.41990774j  0.14791243-0.41990774j
   0.22107788+0.j        ]]


The eigenvalues of a matrix A are scalars that satisfy the equation Av = λv, where v is a non-zero vector and λ is the eigenvalue. This equation means that when the matrix A is multiplied by a vector v, the result is a scalar multiple of the vector v. The vector v is called the eigenvector of the matrix A corresponding to the eigenvalue λ.

The eigenvectors of a matrix A are the non-zero vectors that when multiplied by matrix A, the result is a scalar multiple of that vector. The scalar value is the corresponding eigenvalue of the matrix A.

In terms of the matrix A, its eigenvectors are the non-zero vectors that span the eigenspace of the matrix A and its eigenvalues are the scalars that correspond to the eigenvectors. The eigenvectors are important in many areas of mathematics and physics, and they are often used to diagonalize matrices and to study the stability of systems.